
version: '3.7'

networks:
  default:
    external:
      name: cyber-dojo

services:

  repler:
    build:
      context: server
      args:
         - CYBER_DOJO_RUNNER_HOME=${CYBER_DOJO_RUNNER_HOME}
         - PORT=${CYBER_DOJO_RUNNER_SERVICE_PORT}
         - REPL_PORT=${CYBER_DOJO_REPL_CONTAINER_PORT}
         - NETWORK_NAME=${CYBER_DOJO_NETWORK_NAME}
         - REPL_IMAGE_NAME=${CYBER_DOJO_REPL_IMAGE_NAME}
    user: root
    image: cyberdojo/repler
    init: true
    container_name: test_repler_server
    read_only: false
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CYBER_DOJO_COVERAGE_ROOT
    ports:
      - ${CYBER_DOJO_RUNNER_SERVICE_PORT}:${CYBER_DOJO_RUNNER_SERVICE_PORT}
