
version: '3.7'

#networks:
#  default:
#    external:
#      name: cyber-dojo

services:

  nginx:
    image: cyberdojo/nginx_repler_stub
    build:
      context: nginx_stub
      args: [ COMMIT_SHA ]
    container_name: test_repler_nginx
    env_file: [ .env ]
    depends_on:
      - repler
    init: true
    ports: [ "80:80" ]
    user: root

  repler:
    image: cyberdojo/repler
    build:
      context: server
      args:
         - COMMIT_SHA
         - CYBER_DOJO_REPLER_HOME=${CYBER_DOJO_REPLER_HOME}
         - REPL_PORT=${CYBER_DOJO_REPL_CONTAINER_PORT}
         - NETWORK_NAME=${CYBER_DOJO_NETWORK_NAME}
         - REPL_IMAGE_NAME=${CYBER_DOJO_REPL_IMAGE_NAME}
    ports: [ "${CYBER_DOJO_REPLER_PORT}:${CYBER_DOJO_REPLER_PORT}" ]
    user: root
    init: true
    container_name: test_repler_server
    env_file: [ .env ]
    read_only: false
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
