version: 2
jobs:
  build-image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build image, test it, tag it, publish it
          command: ./build_test_tag_publish.sh server

  log-beta-deployment-to-merkely:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Log beta deployment to Merkely
          command: |
            source ./.circleci/merkely_log_deployment.sh
            merkely_log_deployment beta https://staging.app.merkely.com
            merkely_log_deployment beta https://app.merkely.com

  deploy-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to beta with helm
          command: ./.circleci/deploy_to_namespace.sh beta

  log-prod-deployment-to-merkely:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Log prod deployment to Merkely
          command: |
            source ./.circleci/merkely_log_deployment.sh
            merkely_log_deployment prod https://staging.app.merkely.com
            merkely_log_deployment prod https://app.merkely.com

  deploy-to-prod:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to prod with helm
          command: ./.circleci/deploy_to_namespace.sh prod

workflows:
  version: 2
  build:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only: [ master ]

      - log-beta-deployment-to-merkely:
          context: cyberdojo-context
          requires: [ build-image ]

      - deploy-to-beta:
          context: cyberdojo-context
          requires: [ log-beta-deployment-to-merkely ]

      - approve-to-prod:
          type: approval
          requires: [ deploy-to-beta ]

      - log-prod-deployment-to-merkely:
          context: cyberdojo-context
          requires: [ approve-to-prod ]

      - deploy-to-prod:
          context: cyberdojo-context
          requires: [ log-prod-deployment-to-merkely ]
